# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-28 00:51
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField()),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.Product')),
            ],
        ),
    ]
