# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 00:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_sharding_library.fields
import django_sharding_library.id_generation_strategies


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('home', 'Home'), ('custom', 'Custom')], default='personal', max_length=100)),
                ('custom_type', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('home', 'Home'), ('custom', 'Custom')], default='personal', max_length=100)),
                ('custom_type', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='personal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=django_sharding_library.fields.TableShardedIDField(primary_key=True, serialize=False, source_table_name='contact.ShardedContactIDs', strategy=django_sharding_library.id_generation_strategies.TableStrategy(backing_model_name='contact.ShardedContactIDs')),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
        migrations.AddField(
            model_name='contactemail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
    ]
