# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170617_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_pk',
            new_name='user',
        ),
    ]
